"""Page-level text: titles, sidebar labels, ledes and the prose of each page."""
from common import L

# ---------------------------------------------------------------- page metadata
# nav = sidebar label, title = h1, lede = line under the title (also used on the Contents page)

META = {
    "home": dict(icon="home",
                 nav=L("Overview", "Tổng quan", "Resumen", "概要"),
                 title=L("Automation guide: Facebook, Instagram and TikTok", "Hướng dẫn tự động hoá Facebook, Instagram và TikTok",
                         "Guía de automatización: Facebook, Instagram y TikTok", "自動化ガイド：Facebook・Instagram・TikTok"),
                 lede=L("Install the app, download the packages, import your accounts and run every automation script, step by step, on three platforms.",
                        "Cài ứng dụng, tải package, thêm tài khoản và chạy từng script tự động hoá, từng bước một, trên 3 nền tảng.",
                        "Instala la app, descarga los paquetes, importa tus cuentas y ejecuta cada script de automatización, paso a paso, en tres plataformas.",
                        "アプリのインストール、パッケージのダウンロード、アカウントの登録、各自動化スクリプトの実行までを、3 つのプラットフォームについて手順ごとに解説します。")),
    "contents": dict(icon="list",
                     nav=L("Contents", "Mục lục", "Índice", "目次"),
                     title=L("Contents", "Mục lục", "Índice", "目次"),
                     lede=L("Every page in this guide in one list, grouped the way the sidebar groups them.",
                            "Toàn bộ các trang của tài liệu trong một danh sách, nhóm giống như thanh bên.",
                            "Todas las páginas de la guía en una lista, agrupadas como en la barra lateral.",
                            "このガイドの全ページを、サイドバーと同じまとまりで一覧にしています。")),
    "accounts": dict(icon="id",
                     nav=L("Import accounts", "Thêm tài khoản", "Importar cuentas", "アカウントの登録"),
                     title=L("Add accounts to Account Manager", "Thêm tài khoản vào Account Manager",
                             "Añadir cuentas a Account Manager", "Account Manager へのアカウント追加"),
                     lede=L("Import your accounts into a table, then bind each account to a phone. The steps are the same for Facebook, Instagram and TikTok.",
                            "Nhập tài khoản vào một bảng, sau đó gán mỗi tài khoản cho một điện thoại. Các bước giống nhau cho Facebook, Instagram và TikTok.",
                            "Importa tus cuentas en una tabla y asigna cada cuenta a un teléfono. Los pasos son los mismos para Facebook, Instagram y TikTok.",
                            "アカウントをテーブルに取り込み、各アカウントを端末に割り当てます。手順は Facebook・Instagram・TikTok で共通です。")),
    "rules": dict(icon="clip",
                  nav=L("Before you run a script", "Trước khi chạy script", "Antes de ejecutar un script", "スクリプト実行前の確認"),
                  title=L("Before you run a script", "Trước khi chạy script", "Antes de ejecutar un script", "スクリプト実行前の確認"),
                  lede=L("The checks every script asks for, the rule for new setups, and the path every script follows.",
                         "Những điều mọi script đều yêu cầu kiểm tra, quy tắc khi mới bắt đầu, và trình tự mà script nào cũng đi theo.",
                         "Las comprobaciones que pide cada script, la regla para empezar y el recorrido que siguen todos los scripts.",
                         "どのスクリプトでも求められる確認事項、使い始めのルール、すべてのスクリプトに共通する流れをまとめています。")),
    "apk": dict(icon="box",
                nav=L("Install the app", "Cài ứng dụng", "Instalar la app", "アプリのインストール"),
                title=L("Install the {p} app", "Cài đặt ứng dụng {p}", "Instalar la app de {p}", "{p} アプリのインストール"),
                lede=L("Install the {p} app on every phone at once, from the GenFarmer Control Center.",
                       "Cài ứng dụng {p} lên tất cả điện thoại cùng lúc từ Control Center của GenFarmer.",
                       "Instala la app de {p} en todos los teléfonos a la vez, desde el Control Center de GenFarmer.",
                       "GenFarmer の Control Center から、すべての端末に {p} アプリを一度にインストールします。")),
    "store": dict(icon="grid",
                  nav=L("Download the packages", "Tải package", "Descargar los paquetes", "パッケージの入手"),
                  title=L("Download the {p} packages", "Tải package tự động hoá {p}", "Descargar los paquetes de {p}", "{p} パッケージのダウンロード"),
                  lede=L("Download the three {p} automation packages from the GenFarmer Store.",
                         "Tải 3 package tự động hoá {p} từ Store của GenFarmer.",
                         "Descarga los tres paquetes de automatización de {p} desde la Store de GenFarmer.",
                         "GenFarmer の Store から、{p} の自動化パッケージを 3 つダウンロードします。")),
    "login": dict(icon="id",
                  nav=L("Auto Login", "Auto Login", "Auto Login", "Auto Login"),
                  title=L("AUTO LOGIN {P}", "AUTO LOGIN {P}", "AUTO LOGIN {P}", "AUTO LOGIN {P}"),
                  lede=L("Sign the {p} accounts in your table into the phones automatically.",
                         "Tự động đăng nhập các tài khoản {p} trong bảng vào điện thoại.",
                         "Inicia sesión automáticamente en los teléfonos con las cuentas de {p} de tu tabla.",
                         "テーブルの {p} アカウントを、端末に自動でログインさせます。")),
    "trust": dict(icon="spark",
                  nav=L("Trust", "Trust", "Trust", "Trust"),
                  title=L("GENFARMER {P} TRUST", "GENFARMER {P} TRUST", "GENFARMER {P} TRUST", "GENFARMER {P} TRUST"),
                  lede=L("Nurture the {p} accounts and keep their profiles up to date: {n} functions.",
                         "Nuôi dưỡng tài khoản {p}, tăng độ tin cậy và cập nhật thông tin tài khoản: {n} chức năng.",
                         "Cuida las cuentas de {p} y mantén sus perfiles al día: {n} funciones.",
                         "{p} アカウントを育成し、プロフィールを最新に保ちます。機能は {n} 個です。")),
    "boost": dict(icon="bot",
                  nav=L("Boost", "Boost", "Boost", "Boost"),
                  title=L("GENFARMER {P} BOOST", "GENFARMER {P} BOOST", "GENFARMER {P} BOOST", "GENFARMER {P} BOOST"),
                  lede=L("Increase interaction on {p}: seeding, messages and posting. {n} functions.",
                         "Tăng tương tác trên {p}: seeding, tin nhắn, đăng bài. {n} chức năng.",
                         "Aumenta la interacción en {p}: seeding, mensajes y publicaciones. {n} funciones.",
                         "{p} でのやり取りを増やします：シーディング、メッセージ、投稿。機能は {n} 個です。")),
    "ref-matrix": dict(icon="list",
                       nav=L("All functions", "Bảng tra chức năng", "Todas las funciones", "機能一覧"),
                       title=L("All functions", "Bảng tra chức năng", "Todas las funciones", "機能一覧"),
                       lede=L("Every script and function on the three platforms, with the exact item to pick in the RUN menu.",
                              "Toàn bộ script và chức năng của 3 nền tảng, kèm đúng tên mục cần chọn trong menu RUN.",
                              "Todos los scripts y funciones de las tres plataformas, con la opción exacta que hay que elegir en el menú RUN.",
                              "3 つのプラットフォームの全スクリプトと機能を、RUN メニューで選ぶ項目名とあわせて一覧にしています。")),
    "ref-fields": dict(icon="book",
                       nav=L("Configuration fields", "Các trường cấu hình", "Campos de configuración", "設定項目"),
                       title=L("Configuration fields", "Các trường cấu hình", "Campos de configuración", "設定項目"),
                       lede=L("What every field in Config app means, and which functions use it.",
                              "Ý nghĩa của từng trường trong Config app, và chức năng nào dùng trường đó.",
                              "Qué significa cada campo de Config app y qué funciones lo usan.",
                              "Config app の各項目の意味と、その項目を使う機能をまとめています。")),
    "ref-files": dict(icon="clip",
                      nav=L("Text files", "File text", "Archivos de texto", "テキストファイル"),
                      title=L("Preparing text files", "Chuẩn bị file text", "Preparar archivos de texto", "テキストファイルの準備"),
                      lede=L("Some functions read comments, names, bios or usernames from a text file on your computer. This is how to prepare one.",
                             "Một số chức năng đọc bình luận, name, bi-o hoặc username từ file text trên máy tính. Đây là cách chuẩn bị file.",
                             "Algunas funciones leen comentarios, nombres, biografías o nombres de usuario de un archivo de texto de tu ordenador. Así se prepara.",
                             "一部の機能は、パソコン上のテキストファイルからコメント・名前・自己紹介・ユーザー名を読み込みます。その準備方法です。")),
}

# ---------------------------------------------------------------- home

HOME = {
    "cover_w1": L("GenFarmer <b>Automation Guide</b>", "GenFarmer <b>Tự động hoá</b>", "GenFarmer <b>Automatización</b>", "GenFarmer <b>自動化ガイド</b>"),
    "cover_w2": L("Facebook · Instagram · TikTok · Version {v} · 10/2026", "Facebook · Instagram · TikTok · Phiên bản {v} · 10/2026",
                  "Facebook · Instagram · TikTok · Versión {v} · 10/2026", "Facebook · Instagram · TikTok · バージョン {v} · 2026/10"),
    "intro": L("All three platforms follow the same four stages, in the same order. Learn them once on one platform and the other two will look familiar.",
               "Cả 3 nền tảng đều đi qua cùng 4 giai đoạn, theo cùng một thứ tự. Nắm được một nền tảng thì hai nền tảng còn lại sẽ rất quen thuộc.",
               "Las tres plataformas siguen las mismas cuatro etapas, en el mismo orden. Apréndelas una vez en una plataforma y las otras dos te resultarán familiares.",
               "3 つのプラットフォームはどれも、同じ 4 つの段階を同じ順番で進みます。1 つ覚えれば、残りの 2 つもすぐに分かります。"),
    "flow": [
        (L("Stage 1", "Bước 1", "Etapa 1", "段階 1"), L("Install the app", "Cài ứng dụng", "Instalar la app", "アプリを入れる"),
         L("APK on every phone", "APK lên mọi điện thoại", "APK en cada teléfono", "全端末に APK")),
        (L("Stage 2", "Bước 2", "Etapa 2", "段階 2"), L("Download packages", "Tải package", "Descargar paquetes", "パッケージを入手"),
         L("From the Store", "Từ Store", "Desde la Store", "Store から")),
        (L("Stage 3", "Bước 3", "Etapa 3", "段階 3"), L("Import accounts", "Thêm tài khoản", "Importar cuentas", "アカウントを登録"),
         L("Account Manager", "Account Manager", "Account Manager", "Account Manager")),
        (L("Stage 4", "Bước 4", "Etapa 4", "段階 4"), L("Run scripts", "Chạy script", "Ejecutar scripts", "スクリプトを実行"),
         L("Login · Trust · Boost", "Login · Trust · Boost", "Login · Trust · Boost", "Login · Trust · Boost")),
    ],
    "platforms": L("Three platforms", "Ba nền tảng", "Tres plataformas", "3 つのプラットフォーム"),
    "card_meta": L("{n} functions in 3 packages", "{n} chức năng trong 3 package", "{n} funciones en 3 paquetes", "3 つのパッケージ・{n} 個の機能"),
    "card_go": L("Start with {p}", "Bắt đầu với {p}", "Empezar con {p}", "{p} から始める"),
    "read_first": L("<strong>Read these first.</strong> <a href=\"#/accounts\">Add accounts to Account Manager</a> is shared by all three platforms, and <a href=\"#/rules\">Before you run a script</a> lists the checks every script asks for.",
                    "<strong>Nên đọc trước.</strong> <a href=\"#/accounts\">Thêm tài khoản vào Account Manager</a> dùng chung cho cả 3 nền tảng, và <a href=\"#/rules\">Trước khi chạy script</a> liệt kê những điều mọi script đều yêu cầu kiểm tra.",
                    "<strong>Lee esto primero.</strong> <a href=\"#/accounts\">Añadir cuentas a Account Manager</a> es común a las tres plataformas, y <a href=\"#/rules\">Antes de ejecutar un script</a> reúne las comprobaciones que pide cada script.",
                    "<strong>最初に読んでください。</strong><a href=\"#/accounts\">Account Manager へのアカウント追加</a>は 3 つのプラットフォームで共通です。<a href=\"#/rules\">スクリプト実行前の確認</a>には、どのスクリプトでも必要な確認事項をまとめています。"),
    "where": L("Where to go", "Tìm nhanh", "Adónde ir", "目的別の案内"),
    "col_want": L("I want to…", "Tôi muốn…", "Quiero…", "やりたいこと"),
    "col_go": L("Go to", "Xem trang", "Ve a", "参照先"),
    "w_install": L("Install the app on the phones", "Cài ứng dụng lên điện thoại", "Instalar la app en los teléfonos", "端末にアプリを入れる"),
    "w_accounts": L("Import accounts and bind them to devices", "Thêm tài khoản và gán cho thiết bị", "Importar cuentas y asignarlas a dispositivos", "アカウントを登録して端末に割り当てる"),
    "w_fields": L("Look up what a field in Config app means", "Tra ý nghĩa một trường trong Config app", "Consultar qué significa un campo de Config app", "Config app の項目の意味を調べる"),
    "w_matrix": L("Find which function does what", "Tìm chức năng nào làm gì", "Saber qué hace cada función", "どの機能が何をするか調べる"),
    "w_files": L("Prepare a comment, name or bio file", "Chuẩn bị file bình luận, name hoặc bi-o", "Preparar un archivo de comentarios, nombres o biografías", "コメント・名前・自己紹介のファイルを準備する"),
}

# ---------------------------------------------------------------- accounts

ACC = {
    "prepare": L("<strong>You must prepare the accounts beforehand.</strong>", "<strong>Bạn cần phải chuẩn bị trước các tài khoản.</strong>",
                 "<strong>Debes preparar las cuentas de antemano.</strong>", "<strong>アカウントは事前に用意しておく必要があります。</strong>"),
    "one_table": L("Each script asks you to pick the account table of its platform, so keep one table per platform.",
                   "Mỗi script đều yêu cầu chọn bảng tài khoản của nền tảng tương ứng, vì vậy nên tạo mỗi nền tảng một bảng riêng.",
                   "Cada script te pide elegir la tabla de cuentas de su plataforma, así que usa una tabla por plataforma.",
                   "どのスクリプトでもそのプラットフォームのアカウントテーブルを選ぶため、プラットフォームごとにテーブルを分けておきます。"),
    "h_format": L("The 2FA account format", "Định dạng tài khoản 2FA", "Formato de cuenta 2FA", "2FA アカウントの形式"),
    "format_p": L("The data must be separated by <code>|</code>. For example:", "Bắt buộc các dữ liệu phải được phân biệt bằng dấu <code>|</code>. Ví dụ:",
                  "Los datos deben ir separados por <code>|</code>. Por ejemplo:", "データは必ず <code>|</code> で区切ります。例："),
    "first3": L("For this kind of account you only need the first three values:", "Đối với loại tài khoản này, bạn chỉ cần quan tâm 3 dữ liệu đầu tiên:",
                "Para este tipo de cuenta solo necesitas los tres primeros valores:", "この形式では、最初の 3 つの値だけを使います。"),
    "v_uid": L("<strong>UID</strong>: the login name", "<strong>UID</strong>: tên đăng nhập", "<strong>UID</strong>: el nombre de inicio de sesión", "<strong>UID</strong>：ログイン名"),
    "v_pass": L("<strong>Password</strong>: the login password", "<strong>Password</strong>: mật khẩu đăng nhập", "<strong>Password</strong>: la contraseña", "<strong>Password</strong>：ログインパスワード"),
    "v_2fa": L("<strong>2FA</strong>: the secret used to get the verification code", "<strong>2FA</strong>: chuỗi dùng để lấy code xác thực",
               "<strong>2FA</strong>: la clave con la que se obtiene el código de verificación", "<strong>2FA</strong>：認証コードの取得に使うシークレット"),
    "v_rest": L("Not used", "Không cần dùng", "No se usa", "使用しません"),
    "h_import": L("Import the accounts", "Nhập tài khoản", "Importar las cuentas", "アカウントを取り込む"),
    "s1": L("Choose <strong>ACCOUNT MANAGER</strong>.", "Chọn mục <strong>ACCOUNT MANAGER</strong>.", "Elige <strong>ACCOUNT MANAGER</strong>.", "<strong>ACCOUNT MANAGER</strong> を選びます。"),
    "s2": L("Choose <strong>NEW</strong>, then <strong>NEW TABLE</strong> to create a new data table.",
            "Chọn <strong>NEW</strong>, tiếp tục chọn <strong>NEW TABLE</strong> để tạo một bảng dữ liệu mới.",
            "Elige <strong>NEW</strong> y luego <strong>NEW TABLE</strong> para crear una tabla de datos nueva.",
            "<strong>NEW</strong> を選び、続けて <strong>NEW TABLE</strong> を選んで新しいテーブルを作ります。"),
    "s3": L("Rename the table so it is easy to recognise.", "Đổi tên bảng để dễ dàng nhận biết.",
            "Cambia el nombre de la tabla para reconocerla fácilmente.", "見分けやすいようにテーブル名を変更します。"),
    "s4": L("Choose <strong>ADD ACCOUNT</strong>.", "Chọn mục <strong>ADD ACCOUNT</strong>.", "Elige <strong>ADD ACCOUNT</strong>.", "<strong>ADD ACCOUNT</strong> を選びます。"),
    "s5": L("Copy your accounts and paste them into the <strong>TEXT AREA</strong> box.", "Copy và paste các tài khoản của bạn vào ô <strong>TEXT AREA</strong>.",
            "Copia tus cuentas y pégalas en el cuadro <strong>TEXT AREA</strong>.", "アカウントをコピーし、<strong>TEXT AREA</strong> 欄に貼り付けます。"),
    "s6": L("Open <strong>Select format</strong> and choose <strong>Custom</strong>.", "Chọn mục <strong>Select format</strong> và chọn <strong>Custom</strong>.",
            "Abre <strong>Select format</strong> y elige <strong>Custom</strong>.", "<strong>Select format</strong> を開き、<strong>Custom</strong> を選びます。"),
    "s7": L("Pick the matching field for each value:", "Chọn trường dữ liệu tương ứng:", "Elige el campo que corresponde a cada valor:", "各値に対応する項目を選びます。"),
    "data_n": L("Data {n}", "Dữ liệu {n}", "Dato {n}", "データ {n}"),
    "s8": L("Choose <strong>ADD</strong>.", "Chọn mục <strong>ADD</strong>.", "Elige <strong>ADD</strong>.", "<strong>ADD</strong> を選びます。"),
    "added": L("This is the result once the accounts are added.", "Đây là kết quả sau khi bạn thêm thành công.",
               "Este es el resultado cuando las cuentas se han añadido.", "アカウントを追加し終えたときの画面です。"),
    "h_bind": L("Bind each account to a device", "Gán ID thiết bị cho tài khoản", "Asignar cada cuenta a un dispositivo", "アカウントを端末に割り当てる"),
    "s9": L("Go back to the main screen of the GenFarmer app and choose <strong>CONTROL CENTER</strong>.",
            "Quay lại giao diện chính của app GenFarmer, chọn mục <strong>CONTROL CENTER</strong>.",
            "Vuelve a la pantalla principal de la app GenFarmer y elige <strong>CONTROL CENTER</strong>.",
            "GenFarmer アプリのメイン画面に戻り、<strong>CONTROL CENTER</strong> を選びます。"),
    "s10": L("Select all the devices under <strong>All Devices</strong>.", "Chọn tất cả các thiết bị ở mục <strong>All Devices</strong>.",
             "Selecciona todos los dispositivos en <strong>All Devices</strong>.", "<strong>All Devices</strong> ですべての端末を選択します。"),
    "s11": L("Right-click any phone screen to open the <strong>CONTEXT MENU</strong> and choose <strong>COPY ID</strong>.",
             "Nhấn chuột phải vào một màn hình điện thoại để mở <strong>CONTEXT MENU</strong> và chọn <strong>COPY ID</strong>.",
             "Haz clic derecho en la pantalla de cualquier teléfono para abrir el <strong>CONTEXT MENU</strong> y elige <strong>COPY ID</strong>.",
             "いずれかの端末の画面を右クリックして <strong>CONTEXT MENU</strong> を開き、<strong>COPY ID</strong> を選びます。"),
    "s12": L("Click <strong>ACCOUNT MANAGER</strong>.", "Click chọn <strong>ACCOUNT MANAGER</strong>.", "Haz clic en <strong>ACCOUNT MANAGER</strong>.", "<strong>ACCOUNT MANAGER</strong> をクリックします。"),
    "s13": L("Click the <strong>DEVICES ID</strong> column.", "Click vào cột <strong>DEVICES ID</strong>.", "Haz clic en la columna <strong>DEVICES ID</strong>.", "<strong>DEVICES ID</strong> 列をクリックします。"),
    "s14": L("Paste (<code>Ctrl+V</code>) the device IDs you copied in step 11 into the <strong>DEVICES ID</strong> column of the table.",
             "Paste (<code>Ctrl+V</code>) ID các thiết bị điện thoại bạn đã copy ở bước 11 vào cột <strong>DEVICES ID</strong> trong bảng.",
             "Pega (<code>Ctrl+V</code>) los ID de dispositivo que copiaste en el paso 11 en la columna <strong>DEVICES ID</strong> de la tabla.",
             "手順 11 でコピーした端末 ID を、テーブルの <strong>DEVICES ID</strong> 列に貼り付けます（<code>Ctrl+V</code>）。"),
    "bound": L("Your accounts are now added, and each one is bound to its device ID.",
               "Bây giờ, bạn đã thêm các tài khoản và gán ID thiết bị tương ứng vào các tài khoản thành công.",
               "Tus cuentas ya están añadidas y cada una está asignada a su ID de dispositivo.",
               "これでアカウントの追加と、各アカウントへの端末 ID の割り当てが完了しました。"),
    "h_hotmail": L("TikTok accounts with Hotmail or Outlook", "Tài khoản TikTok dùng Hotmail hoặc Outlook",
                   "Cuentas de TikTok con Hotmail u Outlook", "Hotmail・Outlook 付きの TikTok アカウント"),
    "hotmail_p": L("There are two common kinds of TikTok account on the market: the 2FA format above, and accounts that come with a Hotmail or Outlook mailbox. The second kind uses this format, and the verification code is read from the mailbox through OAuth2 (Mail Live). The values must be separated by <code>|</code>.",
                   "Có 2 dạng tài khoản TikTok phổ biến trên thị trường hiện nay: dạng 2FA ở trên, và dạng sử dụng hotmail hoặc outlook. Dạng thứ hai có định dạng sau, code xác thực được đọc từ hộp thư qua OAuth2 (Mail Live). Bắt buộc các dữ liệu phải được phân biệt bằng dấu <code>|</code>.",
                   "En el mercado hay dos tipos habituales de cuenta de TikTok: el formato 2FA de arriba y las cuentas que vienen con un buzón de Hotmail u Outlook. Las segundas usan este formato, y el código de verificación se lee del buzón mediante OAuth2 (Mail Live). Los valores deben ir separados por <code>|</code>.",
                   "TikTok アカウントには、上記の 2FA 形式と、Hotmail・Outlook のメールボックスが付いた形式の 2 種類がよく出回っています。後者は次の形式で、認証コードは OAuth2（Mail Live）でメールボックスから読み取られます。値は必ず <code>|</code> で区切ります。"),
    "h4": L("Click the <strong>settings icon</strong>, then <strong>NEW FIELD</strong>.", "Chọn vào <strong>icon cài đặt</strong>, tiếp theo chọn <strong>NEW FIELD</strong>.",
            "Haz clic en el <strong>icono de ajustes</strong> y luego en <strong>NEW FIELD</strong>.", "<strong>設定アイコン</strong>をクリックし、<strong>NEW FIELD</strong> を選びます。"),
    "h5": L("Add the fields <code>email</code>, <code>password_email</code>, <code>refresh_token</code> and <code>client_id</code> to the table.",
            "Thêm các field <code>email</code>, <code>password_email</code>, <code>refresh_token</code>, <code>client_id</code> vào bảng.",
            "Añade a la tabla los campos <code>email</code>, <code>password_email</code>, <code>refresh_token</code> y <code>client_id</code>.",
            "テーブルに <code>email</code>、<code>password_email</code>、<code>refresh_token</code>、<code>client_id</code> の項目を追加します。"),
    "h5w": L("Copy the field names from above so they are exact, and make sure they contain no spaces.",
             "Copy các tên field bên trên để đảm bảo chính xác, chú ý không có khoảng trắng trong các field.",
             "Copia los nombres de los campos de arriba para que sean exactos y comprueba que no tienen espacios.",
             "項目名は上からコピーして正確に入力し、空白が入らないよう注意してください。"),
    "hotmail_bind": L("Then bind the devices exactly as in steps 9 to 14 of <a href=\"#/accounts/bind\">Bind each account to a device</a>.",
                      "Sau đó gán ID thiết bị giống hệt bước 9 đến 14 ở mục <a href=\"#/accounts/bind\">Gán ID thiết bị cho tài khoản</a>.",
                      "Después asigna los dispositivos igual que en los pasos 9 a 14 de <a href=\"#/accounts/bind\">Asignar cada cuenta a un dispositivo</a>.",
                      "その後、<a href=\"#/accounts/bind\">アカウントを端末に割り当てる</a>の手順 9〜14 と同じ方法で端末を割り当てます。"),
}

# ---------------------------------------------------------------- rules

RULES = {
    "h_check": L("Check these first", "Kiểm tra trước", "Comprueba esto primero", "最初に確認すること"),
    "any_p": L("Facebook, Instagram or TikTok", "Facebook, Instagram hoặc TikTok", "Facebook, Instagram o TikTok", "Facebook・Instagram・TikTok"),
    "h_one": L("Start with one account per device", "Bắt đầu với mỗi thiết bị một tài khoản", "Empieza con una cuenta por dispositivo", "まずは 1 台に 1 アカウント"),
    "h_path": L("The path every script follows", "Trình tự chung của mọi script", "El recorrido de cada script", "すべてのスクリプトに共通の流れ"),
    "path_p": L("Every script, on every platform, is run the same way. Only the package, the function and its fields change.",
                "Mọi script trên mọi nền tảng đều chạy theo cùng một cách. Chỉ khác nhau ở package, chức năng và các trường dữ liệu.",
                "Todos los scripts, en todas las plataformas, se ejecutan igual. Solo cambian el paquete, la función y sus campos.",
                "どのプラットフォームのどのスクリプトも、実行方法は同じです。違うのはパッケージ、機能、入力項目だけです。"),
    "flow": [
        ("ACCOUNT MANAGER", L("Pick the table", "Chọn bảng", "Elegir la tabla", "テーブルを選ぶ")),
        ("SETUP AUTOMATION", L("Pick the package", "Chọn package", "Elegir el paquete", "パッケージを選ぶ")),
        ("Config app", L("Fill in the fields", "Nhập dữ liệu", "Rellenar los campos", "項目を入力")),
        ("SAVE", L("Save the config", "Lưu cấu hình", "Guardar la configuración", "設定を保存")),
        (L("Rows", "Ô thứ tự", "Filas", "行番号"), L("Select the devices", "Chọn thiết bị", "Elegir dispositivos", "端末を選ぶ")),
        ("RUN", L("Pick a function", "Chọn chức năng", "Elegir una función", "機能を選ぶ")),
    ],
    "h_ai": L("Fields that drive the AI", "Các trường điều khiển AI", "Campos que guían a la IA", "AI を動かす項目"),
    "ai_p": L("Most functions share a few fields. <strong>API key VILAO</strong> lets the AI generate topics, comments, captions and messages; without it, the system falls back to its default data, or to the samples and files you provide. <strong>Language</strong> sets the language the AI writes in, and <strong>Topic</strong> tells it what the accounts are about.",
              "Hầu hết các chức năng dùng chung một vài trường. <strong>API key VILAO</strong> giúp AI tạo chủ đề, bình luận, caption và tin nhắn; nếu không có, hệ thống dùng dữ liệu mặc định, hoặc dùng bài mẫu và file bạn cung cấp. <strong>Language</strong> là ngôn ngữ AI viết ra, và <strong>Topic</strong> cho AI biết tài khoản xoay quanh chủ đề gì.",
              "La mayoría de las funciones comparten algunos campos. <strong>API key VILAO</strong> permite a la IA generar temas, comentarios, textos y mensajes; sin ella, el sistema recurre a sus datos predeterminados o a los ejemplos y archivos que aportes. <strong>Language</strong> fija el idioma en que escribe la IA y <strong>Topic</strong> le dice de qué tratan las cuentas.",
              "多くの機能には共通の項目があります。<strong>API key VILAO</strong> を入れると、AI がトピック、コメント、キャプション、メッセージを生成します。ない場合は、既定のデータ、または入力したサンプルやファイルが使われます。<strong>Language</strong> は AI が書く言語、<strong>Topic</strong> はアカウントのテーマです。"),
    "ai_more": L("Every field is described in <a href=\"#/ref-fields\">Configuration fields</a>.", "Mọi trường đều được giải thích ở <a href=\"#/ref-fields\">Các trường cấu hình</a>.",
                 "Todos los campos se describen en <a href=\"#/ref-fields\">Campos de configuración</a>.", "すべての項目は<a href=\"#/ref-fields\">設定項目</a>で説明しています。"),
}

# ---------------------------------------------------------------- APK and Store

APK = {
    "a1": L("Download the {p} APK from this link:", "Truy cập đường dẫn sau để tải APK {p} về:",
            "Descarga el APK de {p} desde este enlace:", "次のリンクから {p} の APK をダウンロードします。"),
    "a2": L("Once the APK is downloaded, open the GenFarmer app.", "Sau khi tải APK {p} thành công, bạn mở ứng dụng GenFarmer.",
            "Cuando el APK se haya descargado, abre la app GenFarmer.", "APK のダウンロードが終わったら、GenFarmer アプリを開きます。"),
    "a3": L("Select all the devices under <strong>All Devices</strong>.", "Chọn tất cả các thiết bị ở mục <strong>All Devices</strong>.",
            "Selecciona todos los dispositivos en <strong>All Devices</strong>.", "<strong>All Devices</strong> ですべての端末を選択します。"),
    "a4": L("Right-click any phone screen to open the <strong>CONTEXT MENU</strong> and choose <strong>INSTALL APK</strong>.",
            "Nhấn chuột phải vào một màn hình điện thoại để mở <strong>CONTEXT MENU</strong> và chọn <strong>INSTALL APK</strong>.",
            "Haz clic derecho en la pantalla de cualquier teléfono para abrir el <strong>CONTEXT MENU</strong> y elige <strong>INSTALL APK</strong>.",
            "いずれかの端末の画面を右クリックして <strong>CONTEXT MENU</strong> を開き、<strong>INSTALL APK</strong> を選びます。"),
    "a5": L("Click the file icon.", "Chọn vào biểu tượng file.", "Haz clic en el icono de archivo.", "ファイルのアイコンをクリックします。"),
    "a6": L("Choose the {p} APK file you downloaded in step 1.", "Chọn file APK {p} bạn đã tải về ở bước 1.",
            "Elige el archivo APK de {p} que descargaste en el paso 1.", "手順 1 でダウンロードした {p} の APK ファイルを選びます。"),
    "a7": L("Click <strong>INSTALL</strong> and wait until {p} has installed on the phones.",
            "Chọn <strong>INSTALL</strong> và đợi ứng dụng {p} cài đặt thành công về điện thoại.",
            "Haz clic en <strong>INSTALL</strong> y espera a que {p} se instale en los teléfonos.",
            "<strong>INSTALL</strong> をクリックし、{p} が端末にインストールされるまで待ちます。"),
    "next": L("Next, <a href=\"#/{id}-store\">download the {p} packages</a>.", "Tiếp theo, <a href=\"#/{id}-store\">tải package {p}</a>.",
              "A continuación, <a href=\"#/{id}-store\">descarga los paquetes de {p}</a>.", "次は <a href=\"#/{id}-store\">{p} パッケージのダウンロード</a>です。"),
}

STORE = {
    "h_three": L("The three packages", "3 package", "Los tres paquetes", "3 つのパッケージ"),
    "h_open": L("Open the Store", "Mở Store", "Abrir la Store", "Store を開く"),
    "repeat": L("Steps 1 and 2 are the same for every package. Then repeat steps 3 and 4 for each package below.",
                "Bước 1 và 2 giống nhau cho mọi package. Sau đó lặp lại bước 3 và 4 cho từng package bên dưới.",
                "Los pasos 1 y 2 son iguales para todos los paquetes. Después repite los pasos 3 y 4 para cada paquete de abajo.",
                "手順 1 と 2 はすべてのパッケージで共通です。そのあと、下の各パッケージについて手順 3 と 4 を繰り返します。"),
    "o1": L("Open the GenFarmer app and sign in to your GenFarmer account.", "Mở app GenFarmer, sau đó đăng nhập tài khoản GenFarmer của bạn.",
            "Abre la app GenFarmer e inicia sesión con tu cuenta de GenFarmer.", "GenFarmer アプリを開き、GenFarmer アカウントでログインします。"),
    "o2": L("Choose <strong>STORE</strong>.", "Chọn mục <strong>STORE</strong>.", "Elige <strong>STORE</strong>.", "<strong>STORE</strong> を選びます。"),
    "o3": L("Choose <strong>{P}</strong>, then click the <strong>{pkg}</strong> package.", "Chọn mục <strong>{P}</strong>, sau đó nhấn chọn chức năng <strong>{pkg}</strong>.",
            "Elige <strong>{P}</strong> y haz clic en el paquete <strong>{pkg}</strong>.", "<strong>{P}</strong> を選び、<strong>{pkg}</strong> パッケージをクリックします。"),
    "o4": L("Click <strong>DOWNLOAD</strong>, then pick the latest version to download it.", "Chọn mục <strong>DOWNLOAD</strong>, sau đó click chọn phiên bản mới nhất để tải về.",
            "Haz clic en <strong>DOWNLOAD</strong> y elige la versión más reciente para descargarla.", "<strong>DOWNLOAD</strong> をクリックし、最新バージョンを選んでダウンロードします。"),
    "done": L("{pkg} once it has downloaded.", "Giao diện sau khi bạn tải {pkg} thành công.", "{pkg} una vez descargado.", "ダウンロード後の {pkg}。"),
}

# ---------------------------------------------------------------- scripts

SCRIPT = {
    "h_run_login": L("Run AUTO LOGIN {P}", "Chạy AUTO LOGIN {P}", "Ejecutar AUTO LOGIN {P}", "AUTO LOGIN {P} を実行する"),
    "need_acc": L("The accounts must already be in Account Manager and bound to devices. See <a href=\"#/accounts\">Add accounts to Account Manager</a>.",
                  "Tài khoản phải được thêm vào Account Manager và gán ID thiết bị trước. Xem <a href=\"#/accounts\">Thêm tài khoản vào Account Manager</a>.",
                  "Las cuentas deben estar ya en Account Manager y asignadas a dispositivos. Consulta <a href=\"#/accounts\">Añadir cuentas a Account Manager</a>.",
                  "アカウントは事前に Account Manager に登録し、端末に割り当てておく必要があります。<a href=\"#/accounts\">Account Manager へのアカウント追加</a>を参照してください。"),
    "fill_login": L("Enter the data to run the function", "Nhập dữ liệu để chạy chức năng", "Introduce los datos para ejecutar la función", "機能を実行するためのデータを入力します"),
    "hotmail_login": L("Logging in with Hotmail or Outlook accounts (OAuth2)? The table must have the four fields <code>email</code>, <code>password_email</code>, <code>refresh_token</code> and <code>client_id</code>. See <a href=\"#/accounts/hotmail\">TikTok accounts with Hotmail or Outlook</a>.",
                       "Đăng nhập bằng tài khoản Hotmail hoặc Outlook (OAuth2)? Bảng phải có đủ 4 trường <code>email</code>, <code>password_email</code>, <code>refresh_token</code>, <code>client_id</code>. Xem <a href=\"#/accounts/hotmail\">Tài khoản TikTok dùng Hotmail hoặc Outlook</a>.",
                       "¿Inicias sesión con cuentas de Hotmail u Outlook (OAuth2)? La tabla debe tener los cuatro campos <code>email</code>, <code>password_email</code>, <code>refresh_token</code> y <code>client_id</code>. Consulta <a href=\"#/accounts/hotmail\">Cuentas de TikTok con Hotmail u Outlook</a>.",
                       "Hotmail・Outlook アカウント（OAuth2）でログインする場合は、テーブルに <code>email</code>、<code>password_email</code>、<code>refresh_token</code>、<code>client_id</code> の 4 項目が必要です。<a href=\"#/accounts/hotmail\">Hotmail・Outlook 付きの TikTok アカウント</a>を参照してください。"),
    "same_open": L("Steps 1 to 5 are the same for every function below. After step 5, go to the function you want.",
                   "Bước 1 đến 5 giống nhau cho mọi chức năng bên dưới. Sau bước 5, chuyển tới chức năng bạn muốn dùng.",
                   "Los pasos 1 a 5 son iguales para todas las funciones de abajo. Después del paso 5, ve a la función que quieras.",
                   "手順 1〜5 は、下のすべての機能で共通です。手順 5 のあと、使いたい機能に進みます。"),
    "in_menu": L("In the RUN menu: <code>{label}</code>", "Trong menu RUN: <code>{label}</code>", "En el menú RUN: <code>{label}</code>", "RUN メニューの項目：<code>{label}</code>"),
}

# ---------------------------------------------------------------- reference

REF = {
    "matrix_scripts": L("{n} functions across {s} scripts.", "{n} chức năng trong {s} script.", "{n} funciones en {s} scripts.", "{s} 本のスクリプト、{n} 個の機能。"),
    "files_rules": L("Rules for every file", "Quy tắc chung", "Reglas para cualquier archivo", "共通のルール"),
    "f1": L("Use a plain text document (<code>.txt</code>).", "Dùng file text document (<code>.txt</code>).",
            "Usa un documento de texto plano (<code>.txt</code>).", "プレーンテキストのファイル（<code>.txt</code>）を使います。"),
    "f2": L("Put one entry per line: one comment, one name, one bio or one username.", "Mỗi dòng là một thông tin: một bình luận, một name, một bi-o hoặc một username.",
            "Escribe una entrada por línea: un comentario, un nombre, una biografía o un nombre de usuario.", "1 行に 1 件ずつ書きます（コメント、名前、自己紹介、ユーザー名のいずれか 1 つ）。"),
    "f3": L("Enter the full path of the file in the field, for example <code>C:\\Users\\ADMIN\\Document\\file_name.txt</code>.",
            "Nhập đường dẫn đầy đủ của file vào trường dữ liệu, ví dụ <code>C:\\Users\\ADMIN\\Document\\file_name.txt</code>.",
            "Introduce la ruta completa del archivo en el campo, por ejemplo <code>C:\\Users\\ADMIN\\Document\\file_name.txt</code>.",
            "項目にはファイルのフルパスを入力します。例：<code>C:\\Users\\ADMIN\\Document\\file_name.txt</code>"),
    "f4": L("Topics and AI-guided comments typed straight into the form are different: there, separate entries with <code>|</code> instead of new lines.",
            "Khác với file: chủ đề và bình luận định hướng nhập trực tiếp vào form thì phân cách bằng dấu <code>|</code>, không xuống dòng.",
            "Los temas y comentarios guía que escribes directamente en el formulario son distintos: ahí se separan con <code>|</code>, no con saltos de línea.",
            "フォームに直接入力するトピックや AI ガイド用コメントは別です。改行ではなく <code>|</code> で区切ります。"),
    "h_example": L("Example: a comment file", "Ví dụ: file bình luận", "Ejemplo: un archivo de comentarios", "例：コメントファイル"),
    "example": L("Great video, thanks for sharing!\nThis is really useful.\nWhere can I buy this?",
                 "Video hay quá, cảm ơn bạn đã chia sẻ!\nThông tin rất hữu ích.\nMua sản phẩm này ở đâu vậy bạn?",
                 "¡Muy buen vídeo, gracias por compartir!\nEsto es muy útil.\n¿Dónde puedo comprarlo?",
                 "素敵な動画をありがとうございます！\nとても参考になりました。\nこれはどこで買えますか？"),
    "h_which": L("Which functions read a file", "Chức năng nào đọc file", "Qué funciones leen un archivo", "ファイルを読み込む機能"),
    "h_fbcols": L("Facebook: columns instead of files", "Facebook: dùng cột thay cho file", "Facebook: columnas en lugar de archivos", "Facebook：ファイルの代わりに列を使う"),
    "fbcols_p": L("On Facebook, <em>Update avatar</em>, <em>Change cover photo</em> and <em>Change name</em> do not read a file. You add a column to the account table (<code>img</code> or <code>name</code>) and paste an image path, a folder path or the names into it. See <a href=\"#/fb-trust\">GENFARMER FACEBOOK TRUST</a>.",
                  "Trên Facebook, <em>Cập nhật avatar</em>, <em>Đổi ảnh bìa</em> và <em>Đổi tên</em> không đọc file. Bạn thêm một cột vào bảng tài khoản (<code>img</code> hoặc <code>name</code>) rồi paste đường dẫn ảnh, đường dẫn folder hoặc các name vào cột đó. Xem <a href=\"#/fb-trust\">GENFARMER FACEBOOK TRUST</a>.",
                  "En Facebook, <em>Actualizar foto de perfil</em>, <em>Cambiar foto de portada</em> y <em>Cambiar nombre</em> no leen un archivo. Añades una columna a la tabla de cuentas (<code>img</code> o <code>name</code>) y pegas en ella la ruta de una imagen, de una carpeta o los nombres. Consulta <a href=\"#/fb-trust\">GENFARMER FACEBOOK TRUST</a>.",
                  "Facebook の<em>プロフィール画像の更新</em>、<em>カバー写真の変更</em>、<em>名前の変更</em>はファイルを読み込みません。アカウントテーブルに列（<code>img</code> または <code>name</code>）を追加し、画像やフォルダーのパス、名前を貼り付けます。<a href=\"#/fb-trust\">GENFARMER FACEBOOK TRUST</a> を参照してください。"),
    "col_file": L("File holds", "Nội dung file", "Contenido del archivo", "ファイルの中身"),
    "comments": L("Comments", "Bình luận", "Comentarios", "コメント"),
}
