"""Per-platform content: APK, Store packages, scripts and their functions.

Images are referenced by the first 10 hex chars of the MD5 of the PNG extracted
from the source PDF; build.py loads images/<hash>.jpg.

Menu labels (`label`) are copied from the screenshots of the GenFarmer app,
not from the PDF text, because the app is what the reader clicks.
"""
from common import L

# ---------------------------------------------------------------- function descriptions shared by platforms

D = {
    "login": L("Signs the {p} accounts in your table into the phones automatically.",
               "Tự động đăng nhập các tài khoản {p} vào điện thoại.",
               "Inicia sesión automáticamente en los teléfonos con las cuentas de {p} de tu tabla.",
               "テーブルの {p} アカウントを、端末に自動でログインさせます。"),
    "nurture": L("The system uses AI to warm your accounts up automatically, around the topic, audience and industry you are aiming for.",
                 "Hệ thống sử dụng AI để tự động nuôi tài khoản của bạn theo chủ đề, tệp, ngành hàng mà bạn muốn hướng tới.",
                 "El sistema usa IA para calentar tus cuentas automáticamente, según el tema, el público y el sector al que apuntas.",
                 "AI が、狙いたいトピック・客層・業種に合わせてアカウントを自動で育成します。"),
    "avatar": L("The system automatically updates the profile picture of your {p} accounts.",
                "Hệ thống tự động cập nhật ảnh đại diện (avatar) cho các tài khoản {p} của bạn.",
                "El sistema actualiza automáticamente la foto de perfil de tus cuentas de {p}.",
                "{p} アカウントのプロフィール画像を自動で更新します。"),
    "cover": L("The system automatically updates the cover photo of your {p} accounts.",
               "Hệ thống tự động cập nhật ảnh bìa (cover photo) cho các tài khoản {p} của bạn.",
               "El sistema actualiza automáticamente la foto de portada de tus cuentas de {p}.",
               "{p} アカウントのカバー写真を自動で更新します。"),
    "name": L("The system automatically updates the name of your {p} accounts.",
              "Hệ thống tự động cập nhật tên (name) cho các tài khoản {p} của bạn.",
              "El sistema actualiza automáticamente el nombre de tus cuentas de {p}.",
              "{p} アカウントの名前を自動で更新します。"),
    "bio": L("The system automatically updates the bio of your {p} accounts.",
             "Hệ thống tự động cập nhật bi-o cho các tài khoản {p} của bạn.",
             "El sistema actualiza automáticamente la biografía de tus cuentas de {p}.",
             "{p} アカウントの自己紹介（bio）を自動で更新します。"),
    "username": L("The system automatically updates the username of your {p} accounts.",
                  "Hệ thống tự động cập nhật username cho các tài khoản {p} của bạn.",
                  "El sistema actualiza automáticamente el nombre de usuario de tus cuentas de {p}.",
                  "{p} アカウントのユーザー名を自動で更新します。"),
    "reup": L("The system uses AI to find videos related to the topic, audience and industry you care about, downloads them, then posts them again with edits.",
              "Hệ thống sử dụng AI tự động tìm kiếm những video liên quan đến chủ đề, tệp, ngành hàng bạn đang quan tâm để tải về, sau đó đăng lại có chỉnh sửa.",
              "El sistema usa IA para buscar vídeos relacionados con el tema, el público y el sector que te interesan, los descarga y los vuelve a publicar con cambios.",
              "AI が関心のあるトピック・客層・業種に関連する動画を探してダウンロードし、編集を加えて再投稿します。"),
    "seed_link": L("The system uses AI to open the post or reel links you want to seed, and interacts with them for you: like, share, comment, and add views up to the number you want.",
                   "Hệ thống sử dụng AI để tự động truy cập vào link bài viết hoặc link reel mà bạn muốn seeding để tương tác, seeding cho bạn với các tác vụ như like, share, comment, tăng view với số view mong muốn.",
                   "El sistema usa IA para abrir los enlaces de publicaciones o reels que quieres impulsar e interactúa con ellos por ti: me gusta, compartir, comentar y sumar visualizaciones hasta la cifra que quieras.",
                   "AI がシーディングしたい投稿・リールのリンクを開き、いいね、シェア、コメント、希望数までの再生数の追加といったやり取りを代わりに行います。"),
    "seed_video": L("The system uses AI to open the post or video links you want to seed, and interacts with them for you: like, share, comment, and add views up to the number you want.",
                    "Hệ thống sử dụng AI để tự động truy cập vào link bài viết hoặc video mà bạn muốn seeding để tương tác, seeding cho bạn với các tác vụ như like, share, comment, tăng view với số view mong muốn.",
                    "El sistema usa IA para abrir los enlaces de publicaciones o vídeos que quieres impulsar e interactúa con ellos por ti: me gusta, compartir, comentar y sumar visualizaciones hasta la cifra que quieras.",
                    "AI がシーディングしたい投稿・動画のリンクを開き、いいね、シェア、コメント、希望数までの再生数の追加といったやり取りを代わりに行います。"),
    "join_group": L("The system uses AI to find groups on your topics and join them at random.",
                    "Hệ thống sử dụng AI tự động truy cập vào các group theo chủ đề để tham gia ngẫu nhiên.",
                    "El sistema usa IA para buscar grupos sobre tus temas y unirse a ellos al azar.",
                    "AI がトピックに沿ったグループを探し、ランダムに参加します。"),
    "post_group": L("Based on your sample post and images (set in the data), the system uses AI to open groups related to the topics or industries you want to target, then posts content in them.",
                    "Hệ thống sử dụng AI dựa trên dữ liệu bài đăng mẫu và hình ảnh (được cấu hình trong phần dữ liệu) để truy cập các nhóm liên quan theo chủ đề hoặc ngành mà bạn quan tâm và muốn nhắm tới, sau đó đăng nội dung trong các nhóm đó.",
                    "A partir de tu publicación de ejemplo y tus imágenes (configuradas en los datos), el sistema usa IA para entrar en grupos relacionados con los temas o sectores a los que apuntas y publica contenido en ellos.",
                    "設定したサンプル投稿と画像を基に、AI が狙いたいトピックや業種に関連するグループを開き、そこに内容を投稿します。"),
    "seed_comment": L("The system uses AI to process the comments you provide, then writes similar or different comments on your subject and posts them under posts in the related groups you have joined.",
                      "Hệ thống sử dụng AI để xử lý những comment bạn đưa vào, sau đó tạo ra những comment tương tự hoặc khác nhưng có nội dung xoay quanh vấn đề của bạn để comment vào các bài viết trong các hội nhóm liên quan đến chủ đề quan tâm đã tham gia.",
                      "El sistema usa IA para procesar los comentarios que le das y escribe comentarios parecidos o distintos sobre tu tema, que publica en las publicaciones de los grupos relacionados a los que te has unido.",
                      "AI が入力されたコメントを処理し、テーマに沿った似たコメントや別のコメントを作成して、参加済みの関連グループの投稿にコメントします。"),
    "seed_live_fb": L("The system uses the livestream link you enter to join the stream and seed it: interact, like, post comments in bulk and so on. You must enter a livestream link to run this function.",
                      "Hệ thống sử dụng liên kết phát trực tiếp mà bạn nhập để truy cập vào luồng phát trực tiếp để seeding, tương tác, thích, spam bình luận, v.v. Bạn cần nhập liên kết phát trực tiếp để chạy chức năng này.",
                      "El sistema usa el enlace del directo que introduces para entrar en la emisión e impulsarla: interactuar, dar me gusta, publicar comentarios en masa, etc. Debes introducir un enlace de directo para ejecutar esta función.",
                      "入力したライブ配信のリンクから配信に入り、やり取り、いいね、コメントの大量投稿などでシーディングします。この機能を実行するには、ライブ配信のリンクが必要です。"),
    "seed_live_tt": L("The system uses AI to open the livestream link you want to interact with and seeds it: like, and post the comments you want in bulk.",
                      "Hệ thống sử dụng AI tự động truy cập vào link livestream mà bạn muốn tương tác để seeding như like, spam comment với những comment bạn mong muốn.",
                      "El sistema usa IA para abrir el enlace del directo con el que quieres interactuar y lo impulsa: dar me gusta y publicar en masa los comentarios que quieras.",
                      "AI がやり取りしたいライブ配信のリンクを開き、いいねや希望するコメントの大量投稿でシーディングします。"),
    "seed_follow": L("The system uses AI to open the profiles you want to seed and interacts with them: follow, like posts, watch stories, comment and more.",
                     "Hệ thống sử dụng AI tự động truy cập vào trang cá nhân mà bạn muốn seeding để tương tác, seeding với các tác vụ như follow, like các bài đăng, xem tin, comment…",
                     "El sistema usa IA para abrir los perfiles que quieres impulsar e interactúa con ellos: seguir, dar me gusta a publicaciones, ver historias, comentar y más.",
                     "AI がシーディングしたいプロフィールを開き、フォロー、投稿へのいいね、ストーリーズの閲覧、コメントなどのやり取りを行います。"),
    "send_msg": L("The system uses AI to write messages, or uses your default message, and sends them to the users you entered.",
                  "Hệ thống sử dụng AI tự động tạo ra các tin nhắn hoặc dùng tin nhắn mặc định để gửi tới các người dùng mà bạn đã nhập.",
                  "El sistema usa IA para escribir mensajes, o usa tu mensaje predeterminado, y los envía a los usuarios que introdujiste.",
                  "AI がメッセージを作成するか既定のメッセージを使い、入力したユーザーに送信します。"),
    "post_media": L("The system automatically posts the videos or images in your folder to the {p} accounts.",
                    "Hệ thống tự động đăng các video hoặc hình ảnh trong folder của bạn lên các tài khoản {p}.",
                    "El sistema publica automáticamente los vídeos o imágenes de tu carpeta en las cuentas de {p}.",
                    "フォルダー内の動画・画像を {p} アカウントに自動で投稿します。"),
    "post_video": L("The system automatically posts the videos in your folder to the {p} accounts.",
                    "Hệ thống tự động đăng các video trong folder của bạn lên các tài khoản {p}.",
                    "El sistema publica automáticamente los vídeos de tu carpeta en las cuentas de {p}.",
                    "フォルダー内の動画を {p} アカウントに自動で投稿します。"),
}

T = {  # function headings
    "nurture": L("Nurturing account", "Nuôi tài khoản", "Calentar cuentas", "アカウント育成"),
    "avatar": L("Update avatar", "Cập nhật avatar", "Actualizar foto de perfil", "プロフィール画像の更新"),
    "cover": L("Change cover photo", "Đổi ảnh bìa", "Cambiar foto de portada", "カバー写真の変更"),
    "name": L("Change name", "Đổi tên", "Cambiar nombre", "名前の変更"),
    "bio": L("Update bio", "Cập nhật bi-o", "Actualizar biografía", "自己紹介の更新"),
    "username": L("Update username", "Cập nhật username", "Actualizar nombre de usuario", "ユーザー名の更新"),
    "reup": L("Re-upload by topic", "Reup theo chủ đề", "Volver a subir por tema", "トピック別の再投稿"),
    "seed_link": L("Seeding for link", "Seeding theo link", "Seeding por enlace", "リンクへのシーディング"),
    "join_group": L("Join group", "Tham gia group", "Unirse a grupos", "グループ参加"),
    "post_group": L("Post to groups", "Đăng bài vào group", "Publicar en grupos", "グループへの投稿"),
    "seed_comment": L("Seeding comment", "Seeding bình luận", "Seeding de comentarios", "コメントのシーディング"),
    "seed_live": L("Seeding livestream", "Seeding livestream", "Seeding de directos", "ライブ配信のシーディング"),
    "seed_follow": L("Seeding, follow user", "Seeding, follow người dùng", "Seeding y seguir usuarios", "シーディングとフォロー"),
    "send_msg": L("Send message to user", "Gửi tin nhắn tới người dùng", "Enviar mensajes a usuarios", "ユーザーへのメッセージ送信"),
    "post_media": L("Post image or video", "Đăng ảnh hoặc video", "Publicar imagen o vídeo", "画像・動画の投稿"),
    "seed_posts": L("Seeding posts", "Seeding bài viết", "Seeding de publicaciones", "投稿へのシーディング"),
    "seed_profile": L("Seeding profiles", "Seeding trang cá nhân", "Seeding de perfiles", "プロフィールへのシーディング"),
    "post_video": L("Post video", "Đăng video", "Publicar vídeo", "動画の投稿"),
}

FEAT = {
    "login": L("Signs the {p} accounts into the phones automatically.",
               "Tự động đăng nhập các tài khoản {p} vào điện thoại.",
               "Inicia sesión automáticamente con las cuentas de {p} en los teléfonos.",
               "{p} アカウントを端末に自動でログインさせます。"),
    "t_nurture": L("Warms accounts up automatically around your industry.", "Tự động nuôi tài khoản theo ngành hàng của bạn.",
                   "Calienta las cuentas automáticamente según tu sector.", "業種に合わせてアカウントを自動で育成します。"),
    "t_search": L("Searches keywords related to your industry automatically.", "Tự động tìm kiếm các từ khoá liên quan đến ngành hàng.",
                  "Busca automáticamente palabras clave relacionadas con tu sector.", "業種に関連するキーワードを自動で検索します。"),
    "t_reup": L("Re-uploads TikTok videos for the industry you are targeting.", "Tự động reup video TikTok theo ngành hàng đang hướng đến.",
                "Vuelve a subir vídeos de TikTok del sector al que apuntas.", "狙っている業種の TikTok 動画を自動で再投稿します。"),
    "t_update": L("Updates account information automatically.", "Tự động cập nhật thông tin tài khoản.",
                  "Actualiza la información de las cuentas automáticamente.", "アカウント情報を自動で更新します。"),
    "b_views": L("Interacts with, and adds views to, the videos you choose to drive traffic to them.",
                 "Tương tác, buff view kéo traffic cho video chỉ định.",
                 "Interactúa con los vídeos que eliges y les suma visualizaciones para atraer tráfico.",
                 "指定した動画にやり取りと再生数を加え、トラフィックを集めます。"),
    "b_ai": L("Uses AI to analyse a video's content and write comments like a real person.",
              "Tự động dùng AI phân tích nội dung của video để tạo ra comment như người thật.",
              "Usa IA para analizar el contenido de un vídeo y escribir comentarios como una persona real.",
              "AI が動画の内容を分析し、人が書いたようなコメントを作成します。"),
    "b_follow": L("Interacts and follows automatically from the links you give.", "Tự động tương tác, follow theo link chỉ định.",
                  "Interactúa y sigue automáticamente a partir de los enlaces que indicas.", "指定したリンクに対して、自動でやり取りとフォローを行います。"),
    "b_post": L("Spins content and publishes posts automatically.", "Tự động spin content, đăng bài.",
                "Reescribe contenido (spin) y publica automáticamente.", "コンテンツをスピンして自動で投稿します。"),
    "b_msg": L("Spins content and sends marketing messages automatically.", "Tự động spin content rải tin nhắn marketing.",
               "Reescribe contenido (spin) y envía mensajes de marketing automáticamente.", "コンテンツをスピンして、マーケティングメッセージを自動で配信します。"),
    "b_live": L("Opens livestream links and drives views and interaction to push traffic to the live session.",
                "Tự động truy cập link livestream, kéo view, kéo tương tác đẩy traffic cho phiên live.",
                "Entra en enlaces de directos y atrae visualizaciones e interacción para impulsar el tráfico de la emisión.",
                "ライブ配信のリンクを開き、再生数とやり取りを集めて配信のトラフィックを伸ばします。"),
}

PKG_SUM = {
    "login": L("Signs your {p} accounts into the phones automatically.",
               "Giúp bạn tự động đăng nhập tài khoản {p} vào các thiết bị điện thoại.",
               "Inicia sesión automáticamente con tus cuentas de {p} en los teléfonos.",
               "{p} アカウントを端末に自動でログインさせます。"),
    "trust": L("Nurtures the accounts and raises the trust of your {p} accounts.",
               "Giúp bạn nuôi dưỡng tài khoản, tăng độ tin cậy cho tài khoản {p}.",
               "Cuida las cuentas y aumenta la confianza de tus cuentas de {p}.",
               "アカウントを育成し、{p} アカウントの信頼度を高めます。"),
    "boost_post": L("Increases interaction: seeding, posting and more.",
                    "Giúp bạn tăng tương tác, seeding, đăng bài…",
                    "Aumenta la interacción: seeding, publicaciones y más.",
                    "やり取りを増やします：シーディング、投稿など。"),
    "boost_video": L("Increases interaction: seeding, posting videos and more.",
                     "Giúp bạn tăng tương tác, seeding, đăng video…",
                     "Aumenta la interacción: seeding, publicación de vídeos y más.",
                     "やり取りを増やします：シーディング、動画の投稿など。"),
}


def fn(key, title, label, desc, fields, config, save, rows, run, custom=None, extra=None):
    """One function of a script. `run` is a list of screenshots after the RUN step."""
    return dict(key=key, title=title, label=label, desc=desc, fields=fields, img_config=config,
                img_save=save, img_rows=rows, img_run=run, custom=custom, extra=extra)


def fb_custom(field, copy_key, gear, addf, copy, paste):
    return dict(f=field, copy=copy_key, imgs=[gear, addf, copy, paste])


X = lambda key, x: (key, x)  # field that takes the {x} placeholder

# ---------------------------------------------------------------- platforms

PLATFORMS = [
    dict(
        id="fb", name="Facebook", upper="FACEBOOK",
        apk="https://apkpure.com/vn/facebook-app/com.facebook.katana/download?utm_content=1008",
        apk_imgs=["3bdc93e5e3", "dd02a5f3aa", "6fff51bbae", "6f63bc867f", "0aaf8d87c9", "d1a437f99c"],
        boost_sum="boost_post",
        store={"login": ["a0111006a9", "0ed85b90b5", "88381fd0fc"],
               "trust": ["682565b8a9", "0f9653f651", "927e948684"],
               "boost": ["43c2d71388", "7f3b7c9f14", "1ce0c31898"]},
        watch="c640fe11e2",
        login=dict(select="2e26b78afb", config="ec972ae342", fields_img="93b7b2a206", fields=["threads"],
                   save="ec2e12f8a0", rows="3b22ab5d6a", label="Login", run=["258c86e139"]),
        trust=dict(select="83c8f6ac36", config="ecef26129c",
                   features=["t_nurture", "t_search", "t_update"],
                   fns=[
                       fn("nurture", T["nurture"], "Nurturing Account", D["nurture"],
                          ["threads", "apikey", "language", "topic_nurture", "aiguide"],
                          "67b0dcd22e", "d817c968c9", "6cbb69e24e", ["6c316656f0"]),
                       fn("avatar", T["avatar"], "Change Avatar", D["avatar"], ["threads"],
                          "20beed3667", "e028a3cf02", "6cbb69e24e", ["d2638b16a4"],
                          custom=fb_custom("img", "s_copy_img", "ef96851388", "26054275e7", "dbc00e104c", "3c80390a93")),
                       fn("cover", T["cover"], "Change Cover Photo", D["cover"], ["threads"],
                          "20beed3667", "e028a3cf02", "6cbb69e24e", ["d2638b16a4"],
                          custom=fb_custom("img", "s_copy_img", "ef96851388", "26054275e7", "dbc00e104c", "3c80390a93")),
                       fn("name", T["name"], "Change name", D["name"], ["threads"],
                          "20beed3667", "e028a3cf02", "6cbb69e24e", ["9f9ca8a1a2"],
                          custom=fb_custom("name", "s_copy_name", "ef96851388", "e4b7362e41", "f3465a1f97", "5c2f76b414")),
                   ]),
        boost=dict(select="f4120a1801", config="0ddd6cbd7b",
                   features=["b_views", "b_ai", "b_follow", "b_post"],
                   fns=[
                       fn("seed_link", T["seed_link"], "Seeding theo link", D["seed_link"],
                          ["threads", "apikey", "topic_related", "language", "links_posts", "goal", "file_comment"],
                          "6c4daec657", "a7c610e993", "a470130f08", ["98d8eefa05"]),
                       fn("join_group", T["join_group"], "Join group", D["join_group"],
                          ["threads", "apikey", "topic_related", "language"],
                          "603cbcce8e", "e4b0188702", "40e42e95e5", ["e6954b7edb"]),
                       fn("post_group", T["post_group"], "Post group", D["post_group"],
                          ["threads", "apikey", "topic_related", "language", "post_sample", "goal", "folder_images_opt"],
                          "66c72d46ef", "6fa336b24a", "23715ec3f5", ["acc33b951c"]),
                       fn("seed_comment", T["seed_comment"], "Seeding comment", D["seed_comment"],
                          ["threads", "apikey", "topic_related", "language", "comment_sample", "goal", "folder_images_opt"],
                          "66c72d46ef", "8a074f6e00", "d424227443", ["f3e4754f93"]),
                       fn("seed_live", T["seed_live"], "Seeding livestream", D["seed_live_fb"],
                          ["threads", "apikey", "topic_related", "language", "live_link", "goal_live", "file_comment"],
                          "e4a079f6a8", "ebfb5fff92", "d424227443", ["bf171c74ec"]),
                   ]),
    ),
    dict(
        id="ig", name="Instagram", upper="INSTAGRAM",
        apk="https://apkpure.com/vn/instagram-app/com.instagram.android/download?utm_content=1008",
        apk_imgs=["3bdc93e5e3", "dd02a5f3aa", "6fff51bbae", "6f63bc867f", "74b7316553", "fa6fae979f"],
        boost_sum="boost_video",
        store={"login": ["202256621c", "a37f49ef65", "1787bd7d15"],
               "trust": ["8dac49dc34", "e2752e7848", "cd0579168d"],
               "boost": ["1d210e92c2", "30efebacb2", "85340bc03a"]},
        watch="e94d39dfe9",
        login=dict(select="f45ca4304c", config="eaaa4fd5f7", fields_img="a0f8fc1b1c", fields=["threads"],
                   save="b2ba2d5cb1", rows="28453af210", label="LOGIN IG", run=["7fed3c660c"]),
        trust=dict(select="255c7237de", config="d238a4196a",
                   features=["t_nurture", "t_search", "t_update"],
                   fns=[
                       fn("nurture", T["nurture"], "Nurture accounts", D["nurture"],
                          ["threads", "apikey", "language", "topic_nurture", "aiguide"],
                          "67b0dcd22e", "af456ffe2b", "fdb3956a8e", ["0f607c8936"]),
                       fn("avatar", T["avatar"], "Update avatar", D["avatar"],
                          ["threads", "img_pick", "folder_avatar"],
                          "ec89c97063", "af456ffe2b", "fdb3956a8e", ["83b0571757"]),
                       fn("name", T["name"], "Update Name", D["name"],
                          ["threads", "apikey", "language", "topic_interest", X("file_or_ai", "name"), X("x_pick", "name"), X("x_file", "name")],
                          "5b17ae38ff", "af456ffe2b", "fdb3956a8e", ["d24e8dc90c"]),
                       fn("bio", T["bio"], "Update bi-o", D["bio"],
                          ["threads", "apikey", "language", "topic_interest", X("file_or_ai", "bio"), X("x_pick", "bio"), X("x_file", "bio")],
                          "a6c1d227ca", "af456ffe2b", "fdb3956a8e", ["f3d2cf9414"]),
                   ]),
        boost=dict(select="e2cf6b9170", config="1af40fc613",
                   features=["b_views", "b_ai", "b_follow", "b_msg"],
                   fns=[
                       fn("seed_link", T["seed_link"], "Seeding For Link", D["seed_link"],
                          ["threads", "language", "apikey", "links_posts", "views_per", "topic_related", "goal", "file_comment"],
                          "9d287e370c", "e16c85ba40", "4ab6d57a6a", ["1534c0a2f3"]),
                       fn("seed_follow", T["seed_follow"], "Seeding, follow User", D["seed_follow"],
                          ["threads", "language", "apikey", "links_profiles", "views_per_opt", "topic_related", "goal", "file_comment"],
                          "5bbbd465cf", "7afe75cca3", "40e42e95e5", ["1df67c4137"]),
                       fn("send_msg", T["send_msg"], "Send Message To User", D["send_msg"],
                          ["threads", "language", "apikey", "links_profiles", "topic_msg", "goal_msg", "msg_template"],
                          "43af034232", "bd08895405", "23715ec3f5", ["1efc62fac8"]),
                       fn("post_media", T["post_media"], "Post video or image", D["post_media"],
                          ["threads", "language", "apikey_caption", "topic_media", "goal_media", "share_story", "folder_media",
                           "ai_video", "delete_after", "hashtags", "caption_tpl"],
                          "cb20d23c8c", "60d79f948d", "d424227443", ["eeabfd2b4f"]),
                   ]),
    ),
    dict(
        id="tt", name="TikTok", upper="TIKTOK",
        apk="https://apkpure.com/vn/tiktok-musically-2025/com.zhiliaoapp.musically/download?utm_content=1008",
        apk_imgs=["3bdc93e5e3", "dd02a5f3aa", "6fff51bbae", "6f63bc867f", "e9c3a86f8e", "fe2b89ea16"],
        boost_sum="boost_video",
        store={"login": ["9a2d596e33", "2819575169", "08db5ae4b2"],
               "trust": ["b36ceda766", "33ba973102", "d755a6b74b"],
               "boost": ["ad36baa36e", "993c1ad561", "8fc3fffd07"]},
        watch="6eb26bf204",
        login=dict(select="5e29c44de7", config="a86c703534", fields_img="72006e0ba4", fields=["threads", "captcha"],
                   save="f1b90fbdd5", rows="cbb88e9d23", label="Đăng nhập TikTok ( Login )", run=["ec91a227df"],
                   hotmail=True),
        trust=dict(select="c0d5f7b5a0", config="32c89ae9df",
                   features=["t_nurture", "t_search", "t_reup", "t_update"],
                   fns=[
                       fn("nurture", T["nurture"], "Nuturing account", D["nurture"],
                          ["threads", "apikey", "language", "topic_nurture", "aiguide", "action_rate"],
                          "690574bc6a", "a7374a27fc", "3f7b4b0e6b", ["fe896c3b95"]),
                       fn("reup", T["reup"], "Reup video", D["reup"],
                          ["threads", "apikey", "language", "topic_reup"],
                          "ed876da969", "2e8f701ea9", "3f7b4b0e6b", ["717d69385b"]),
                       fn("avatar", T["avatar"], "Update Avatar", D["avatar"],
                          ["threads", "folder_avatar"],
                          "3f4065a70f", "2e8f701ea9", "3f7b4b0e6b", ["74fafbff12"]),
                       fn("bio", T["bio"], "Update Bio", D["bio"],
                          ["threads", "apikey", "language", "topic_ai", X("file_or_ai", "bio"), X("x_file", "bio")],
                          "cf6fab5ae8", "2e8f701ea9", "3f7b4b0e6b", ["372ab9675c"]),
                       fn("name", T["name"], "Update name", D["name"],
                          ["threads", "apikey", "language", "topic_ai", X("file_or_ai", "name"), X("x_file", "name")],
                          "4cbc7aeba4", "2e8f701ea9", "3f7b4b0e6b", ["3c30e96114"]),
                       fn("username", T["username"], "update username", D["username"],
                          ["threads", "apikey", "language", "topic_ai", X("file_or_ai", "username"), X("x_file", "username")],
                          "65b7b2c54a", "2e8f701ea9", "3f7b4b0e6b", ["3c30e96114"]),
                   ]),
        boost=dict(select="a4f0a9d46f", config="4c229f62d4",
                   features=["b_views", "b_ai", "b_follow", "b_msg", "b_live"],
                   fns=[
                       fn("seed_posts", T["seed_posts"], "Seeding bài viết", D["seed_video"],
                          ["threads", "apikey", "views_per", "links_posts", "language", "topic_related", "video_goals",
                           "portrait", "file_comment"],
                          "542dd36113", "6edfbf27c3", "eb1c9e3d67", ["dd1ad8a0da"]),
                       fn("seed_profile", T["seed_profile"], "Seeding trang cá nhân", D["seed_follow"],
                          ["threads", "apikey", "views_per_opt", "links_profiles", "language", "topic_related", "video_goals",
                           "portrait", "file_comment", "msg_template"],
                          "5b652822ea", "6edfbf27c3", "eb1c9e3d67", ["320bb0f526"]),
                       fn("seed_live", T["seed_live"], "Seeding livestream", D["seed_live_tt"],
                          ["threads", "apikey", "views_per_opt", "live_link", "language", "topic_live", "video_goals_live",
                           "portrait_live", "file_comment"],
                          "87f64de971", "6edfbf27c3", "eb1c9e3d67", ["d22b61bbcf", "6a20679302"]),
                       fn("post_video", T["post_video"], "Post Video", D["post_video"],
                          ["threads", "apikey", "language", "topic_videos", "folder_videos", "video_count", "delete_after",
                           "ai_video", "hashtags", "caption_mode"],
                          "a9fa875a64", "6edfbf27c3", "eb1c9e3d67", ["25968783df"]),
                   ]),
    ),
]
